# kubernetes-manifests/kustomize/auth-migration-job/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - job.yaml

images:
  - name: authservice # Bu Job da 'authservice' imaj覺n覺 kullan覺yor
    # newName: authservice
    # newTag: "" # Skaffold buray覺 dolduracak