apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: voyago-omega-x

build:
  tagPolicy:
    gitCommit: {}     # Git commit hash’i ile etiketler
  local:
    push: false       # Minikube kullandığımız için push = false
  artifacts:
    - image: authservice
      context: .      # Proje kökünde Dockerfile var
      docker:
        dockerfile: src/core/identity/authservice/Dockerfile

profiles:
  - name: omega-x-dev-platform
    deploy:
      # ─────────────────────────────────────────────────────────────
      # 1) DÜZ YAML’LARI kubectl ile apply et
      kubectl:
        manifests:
          - kubernetes-manifests/postgres-auth/configmap.yaml
          - kubernetes-manifests/postgres-auth/secret.yaml
          - kubernetes-manifests/postgres-auth/pvc.yaml
          - kubernetes-manifests/postgres-auth/deployment.yaml
          - kubernetes-manifests/postgres-auth/service.yaml
          - kubernetes-manifests/auth-jwt-secret.yaml

      # ─────────────────────────────────────────────────────────────
      # 2) KUSTOMIZE KLASÖRLERİNİ ayrı blokta tanımla
      kustomize:
        paths:
          - kubernetes-manifests/kustomize/auth-migration-job
          - kubernetes-manifests/kustomize/authservice

      helm:
        releases:
          - name: voyago-nats
            chartPath: kubernetes-manifests/charts/nats
            valuesFiles:
              - kubernetes-manifests/helm-values/nats/nats-mvp-values.yaml
            namespace: voyago-infra
            createNamespace: true
            wait: true
            # timeout: "Xm" # v2beta29'da bu alan yok

          - name: voyago-kong
            chartPath: kubernetes-manifests/charts/kong
            valuesFiles:
              - kubernetes-manifests/helm-values/kong/kong-mvp-values.yaml
            namespace: voyago-infra
            createNamespace: false 
            wait: true
            # timeout: "15m" # v2beta29'da bu alan yok

          - name: voyago-redis
            chartPath: kubernetes-manifests/charts/redis
            valuesFiles:
              - kubernetes-manifests/helm-values/redis/redis-mvp-values.yaml
            namespace: voyago-infra
            createNamespace: false
            wait: true
            # timeout: "Xm" # v2beta29'da bu alan yok

          - name: voyago-observability 
            chartPath: kubernetes-manifests/charts/kube-prometheus-stack
            valuesFiles:
              - kubernetes-manifests/helm-values/observability/prometheus-grafana-mvp-values.yaml
            namespace: voyago-monitoring
            createNamespace: true
            wait: true
            # timeout: "15m" # v2beta29'da bu alan yok
            skipBuildDependencies: true 

          - name: voyago-observability-loki
            chartPath: kubernetes-manifests/charts/loki-stack
            valuesFiles:
              - kubernetes-manifests/helm-values/observability/loki-mvp-values.yaml
            namespace: voyago-monitoring
            createNamespace: false 
            wait: true
            # timeout: "10m" # v2beta29'da bu alan yok
            skipBuildDependencies: true 
            
          - name: voyago-tempo
            chartPath: kubernetes-manifests/charts/tempo
            valuesFiles:
              - kubernetes-manifests/helm-values/observability/tempo-values.yaml
            namespace: voyago-monitoring
            createNamespace: false
            wait: true
            # timeout: "10m" # v2beta29'da bu alan yok
            skipBuildDependencies: true 
            
          - name: voyago-otel-collector
            chartPath: kubernetes-manifests/charts/opentelemetry-collector
            valuesFiles:
              - kubernetes-manifests/helm-values/observability/otel-collector-mvp-values.yaml
            namespace: voyago-monitoring
            createNamespace: false 
            wait: true
            # timeout: "10m" # v2beta29'da bu alan yok
            skipBuildDependencies: true 

    portForward:
      - resourceType: service
        resourceName: authservice
        namespace: default
        port: 50051
        localPort: 50051
      
      - resourceType: service
        resourceName: postgres-auth-svc
        namespace: default
        port: 5432
        localPort: 5433
      
      - resourceType: service
        resourceName: voyago-nats
        namespace: voyago-infra
        port: 4222
        localPort: 42220
      
      - resourceType: service
        resourceName: voyago-kong-kong-proxy
        namespace: voyago-infra
        port: 8000
        localPort: 8000
      
      - resourceType: service
        resourceName: voyago-kong-kong-admin
        namespace: voyago-infra
        port: 8001
        localPort: 8001
      
      - resourceType: service
        resourceName: voyago-redis-master
        namespace: voyago-infra
        port: 6379
        localPort: 16379
      
      - resourceType: service
        resourceName: voyago-observability-grafana
        namespace: voyago-monitoring
        port: 80
        localPort: 3000
      
      - resourceType: service
        resourceName: voyago-observability-kube-prometheus
        namespace: voyago-monitoring
        port: 9090
        localPort: 9090
      
      - resourceType: service
        resourceName: voyago-observability-kube-alertmanager
        namespace: voyago-monitoring
        port: 9093
        localPort: 9093
      
      - resourceType: service
        resourceName: voyago-tempo
        namespace: voyago-monitoring
        port: 3100
        localPort: 32000
      
      - resourceType: service
        resourceName: voyago-otel-collector-opentelemetry-collector
        namespace: voyago-monitoring
        port: 4317 # OTLP gRPC
        localPort: 43170
      
      - resourceType: service
        resourceName: voyago-otel-collector-opentelemetry-collector
        namespace: voyago-monitoring
        port: 4318 # OTLP HTTP
        localPort: 43180