apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: voyago-base

build:
  artifacts:
    - image: auth-service
      context: src/authservice
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    useDockerCLI: true
    useBuildkit: true

deploy:
  kubectl:
    manifests: []    # Defaultta hiçbir şey deploy etme

profiles:
  - name: auth-dev
    deploy:
      kubectl:
        manifests:
          - kubernetes-manifests/postgres-auth/configmap.yaml
          - kubernetes-manifests/postgres-auth/secret.yaml
          - kubernetes-manifests/postgres-auth/pvc.yaml
          - kubernetes-manifests/postgres-auth/deployment.yaml
          - kubernetes-manifests/postgres-auth/service.yaml
          - kubernetes-manifests/auth-jwt-secret.yaml
          - kubernetes-manifests/authservice.yaml

  - name: infra-dev
    deploy:
      kubectl:
        manifests:
          - kubernetes-manifests/postgres-auth/*.yaml
          - kubernetes-manifests/auth-jwt-secret.yaml

  - name: full-dev
    deploy:
      kubectl:
        manifests:
          - kubernetes-manifests/**/*.yaml
