apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: voyago-omega-x

build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: auth-service
      context: src/authservice
      docker:
        dockerfile: Dockerfile

profiles:
  - name: omega-x-dev-platform
    deploy:
      kubectl:
        manifests:
          # AuthService + Postgres
          - kubernetes-manifests/postgres-auth/configmap.yaml
          - kubernetes-manifests/postgres-auth/secret.yaml
          - kubernetes-manifests/postgres-auth/pvc.yaml
          - kubernetes-manifests/postgres-auth/deployment.yaml
          - kubernetes-manifests/postgres-auth/service.yaml
          - kubernetes-manifests/auth-jwt-secret.yaml
          - kubernetes-manifests/authservice.yaml

      helm:
        releases:
          - name: voyago-nats
            chartPath: kubernetes-manifests/charts/nats
            valuesFiles:
              - kubernetes-manifests/helm-values/nats/nats-mvp-values.yaml
            namespace: voyago-infra
            createNamespace: true
            wait: true

          - name: voyago-kong
            chartPath: kubernetes-manifests/charts/kong
            valuesFiles:
              - kubernetes-manifests/helm-values/kong/kong-mvp-values.yaml
            namespace: voyago-infra
            createNamespace: false
            wait: true

          - name: voyago-redis
            chartPath: kubernetes-manifests/charts/redis
            valuesFiles:
              - kubernetes-manifests/helm-values/redis/redis-mvp-values.yaml
            namespace: voyago-infra
            createNamespace: false   # zaten infra yarattık
            wait: true

          - name: voyago-observability
            chartPath: kubernetes-manifests/charts/kube-prometheus-stack
            valuesFiles:
              - kubernetes-manifests/helm-values/observability/prometheus-grafana-mvp-values.yaml
            namespace: voyago-monitoring
            createNamespace: true
            wait: true

          - name: voyago-observability-loki
            chartPath: kubernetes-manifests/charts/loki-stack
            valuesFiles:
              - kubernetes-manifests/helm-values/observability/loki-mvp-values.yaml
            namespace: voyago-monitoring
            createNamespace: false   # namespace’i bir önceki adımda oluşturduk
            wait: true


    portForward:
      - resourceType: service
        resourceName: authservice
        namespace: default
        port: 50051
        localPort: 50051
      - resourceType: service
        resourceName: postgres-auth-svc
        namespace: default
        port: 5432
        localPort: 5433
      - resourceType: service
        resourceName: voyago-nats
        namespace: voyago-infra
        port: 4222
        localPort: 42220
      - resourceType: service
        resourceName: voyago-kong-kong-proxy
        namespace: voyago-infra
        port: 8000    # <-- artık servicePort=8000
        localPort: 8000
