# voyago-base/skaffold.yaml (TAM VERSİYON)
apiVersion: skaffold/v2beta29 
kind: Config
metadata:
  name: voyago-base
build:
  artifacts:
    - image: auth-service
      context: src/authservice
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    useDockerCLI: true
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/postgres-auth/configmap.yaml
      - kubernetes-manifests/postgres-auth/secret.yaml
      - kubernetes-manifests/auth-jwt-secret.yaml      # JWT Secret
      - kubernetes-manifests/postgres-auth/pvc.yaml
      - kubernetes-manifests/postgres-auth/deployment.yaml
      - kubernetes-manifests/postgres-auth/service.yaml
      - kubernetes-manifests/authservice.yaml             # AuthService