# kubernetes-manifests/auth-jwt-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt-secret     # Secret'ımızın adı
  labels:
    app: voyago-authservice # Bu Secret'ın authservice ile ilgili olduğunu belirtelim
    component: secret
type: Opaque
data:
  # JWT_SECRET_KEY anahtarının değeri base64 encode edilmiş olmalı
  # "jwtSecret" anahtar adını kullanıyoruz, bu authservice.yaml'da referans verilecek
  jwtSecret: Y29rR3VjbHVWZVV6dW5CaXJKd3RTZWNyZXRLZXlpbVZhckJlbmltMTIzIUAj 
  # Örnek: jwtSecret: YnVDb2tHaXpsaUJpckFuYWh0YXJPY2FrMTIzIUAjX1ZveWFHbw==