# voyago-base/kubernetes-manifests/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # PostgreSQL servislerimiz
  - ./postgres-auth/configmap.yaml # ./ ile göreceli yol belirttik
  - ./postgres-auth/secret.yaml
  - ./postgres-auth/pvc.yaml
  - ./postgres-auth/deployment.yaml
  - ./postgres-auth/service.yaml
  # AuthService'imiz
  - authservice.yaml # Bu dosya zaten kubernetes-manifests/ altında