apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
  labels:
    tier: database
    app: voyago-auth
    component: postgresql
spec:
  accessModes:
    - ReadWriteOnce # Tek bir node tarafından okunup yazılabilir
  resources:
    requests:
      storage: 1Gi # Minikube için başlangıçta yeterli, ihtiyaca göre artırılabilir
