apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  labels:
    tier: database
    app: voyago-auth
    component: postgresql
type: Opaque
data:
  POSTGRES_PASSWORD: YXV0aHBhc3N3b3Jk # "authpassword" base64 encoded hali
