nats:
  jetstream:
    enabled: true
    fileStore:
      enabled: true
      size: "1Gi"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  service:
    type: NodePort

# ─────────────────────────────────────────────────────────
# Chart içi test hook’larını ve nats-box’u kapatma:
tests:
  enabled: false

natsBox:
  enabled: false
