# kubernetes-manifests/helm-values/observability/prometheus-grafana-mvp-values.yaml

prometheus:
  enabled: true
  prometheusSpec:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1" 
        memory: "1.5Gi"
    retention: "7d" 
    
grafana:
  enabled: true
  adminPassword: "VoyaGoSuperAdmin123!" 
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

kubeStateMetrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Helm testlerini devre dışı bırak
  tests:
    enabled: false
