name: AuthService CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'src/authservice/**'
      - '.github/workflows/authservice-ci-cd.yaml'
      - 'kubernetes-manifests/**'
      - 'skaffold.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/authservice/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository_owner }}/${{ github.event.repository.name }}
  AUTH_SERVICE_IMAGE_NAME: auth-service
  K8S_NAMESPACE: default

jobs:
  test-unit:
    name: Run AuthService Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/authservice
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: ./src/authservice/go.sum # go.sum yolu belirtildi

      - name: Run Go Tidy
        run: go mod tidy

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Unit Tests (repository & service)
        env: # Unit testler için (özellikle mocklanmayan kısımlar varsa)
          JWT_SECRET_KEY: "ci_unit_test_jwt_secret_123"
        run: |
          echo "Running repository unit tests..."
          go test -v -race -coverprofile=repo_coverage.out -covermode=atomic ./repository/...
          echo "Running service unit tests..."
          go test -v -race -coverprofile=service_coverage.out -covermode=atomic ./service/...
          # Birleştirilmiş coverage için (opsiyonel):
          # echo "mode: atomic" > coverage.out && cat repo_coverage.out service_coverage.out | grep -v mode: | grep -v "^$" >> coverage.out

  build-and-push:
    name: Build & Push AuthService Docker Image
    needs: test-unit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag_sha_short: ${{ steps.meta.outputs.version }} # örn: sha-a1b2c3d
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}/${{ env.AUTH_SERVICE_IMAGE_NAME }}
          tags: |
            type=sha,format=short,prefix=
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/authservice
          file: ./src/authservice/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-and-e2e-test:
    name: Deploy to Minikube & Run E2E Tests
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest
        with:
          cache: true

      - name: Ensure Kubeconfig is set for Minikube
        run: |
          minikube update-context
          kubectl config use-context minikube
          echo "Current Kube context set to Minikube."

      - name: Apply Base Kubernetes Manifests (PostgreSQL, Secrets)
        run: |
          echo "Applying PostgreSQL and Secret manifests to namespace: ${{ env.K8S_NAMESPACE }}"
          kubectl apply -f kubernetes-manifests/postgres-auth/configmap.yaml --namespace=${{ env.K8S_NAMESPACE }}
          kubectl apply -f kubernetes-manifests/postgres-auth/secret.yaml --namespace=${{ env.K8S_NAMESPACE }}
          kubectl apply -f kubernetes-manifests/auth-jwt-secret.yaml --namespace=${{ env.K8S_NAMESPACE }}
          kubectl apply -f kubernetes-manifests/postgres-auth/pvc.yaml --namespace=${{ env.K8S_NAMESPACE }}
          kubectl apply -f kubernetes-manifests/postgres-auth/deployment.yaml --namespace=${{ env.K8S_NAMESPACE }}
          kubectl apply -f kubernetes-manifests/postgres-auth/service.yaml --namespace=${{ env.K8S_NAMESPACE }}
          
          echo "Waiting for PostgreSQL to be ready..."
          kubectl rollout status deployment/postgres-auth-deployment --namespace=${{ env.K8S_NAMESPACE }} --timeout=240s

      - name: Prepare and Run Database Migration Job
        env:
          IMAGE_TO_USE_FOR_MIGRATION: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}/${{ env.AUTH_SERVICE_IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag_sha_short }}
        run: |
          echo "Preparing Database Migration Job manifest using image: ${IMAGE_TO_USE_FOR_MIGRATION}"
          # auth-migration-job.yaml'ı kopyala ve imajı dinamik olarak set et
          cp kubernetes-manifests/auth-migration-job.yaml auth-migration-job-ci.yaml
          # 'image: placeholder-image-will-be-set-by-ci' satırını arıyoruz
          # Bu satırın auth-migration-job.yaml içinde tam olarak bu şekilde olduğundan emin olun!
          sed -i "s|image: placeholder-image-will-be-set-by-ci|image: ${IMAGE_TO_USE_FOR_MIGRATION}|g" auth-migration-job-ci.yaml
          
          echo "Applying and running Database Migration Job..."
          kubectl delete job auth-db-migration-job --namespace=${{ env.K8S_NAMESPACE }} --ignore-not-found=true
          sleep 5 # Silinmesi için bekleme
          kubectl apply -f auth-migration-job-ci.yaml --namespace=${{ env.K8S_NAMESPACE }}
          
          echo "Waiting for Database Migration Job to complete..."
          kubectl wait --for=condition=complete job/auth-db-migration-job --namespace=${{ env.K8S_NAMESPACE }} --timeout=300s
          echo "Database Migration Job completed. Displaying logs (last 50 lines):"
          kubectl logs job/auth-db-migration-job --namespace=${{ env.K8S_NAMESPACE }} --tail=100 || echo "Migration job logs not available or job failed/no logs."
          MIGRATION_SUCCESS=$(kubectl get job auth-db-migration-job -n ${{ env.K8S_NAMESPACE }} -o jsonpath='{.status.succeeded}')
          if [ "$MIGRATION_SUCCESS" != "1" ]; then
            echo "Database migration job failed!"
            # Job pod'unun loglarını çekmeye çalışalım
            MIGRATION_POD_NAME=$(kubectl get pods -n ${{ env.K8S_NAMESPACE }} -l job-name=auth-db-migration-job -o jsonpath='{.items[0].metadata.name}' || echo "")
            if [ -n "$MIGRATION_POD_NAME" ]; then
              echo "--- Migration Pod Logs ---"
              kubectl logs $MIGRATION_POD_NAME -n ${{ env.K8S_NAMESPACE }} || echo "Could not get migration pod logs."
            fi
            exit 1
          fi
          echo "Database migration job succeeded."

      - name: Deploy AuthService with latest image
        env: # JWT_SECRET_KEY'i burada da tanımlayalım ki AuthService pod'u doğru secret'ı alsın
          # Aslında bu K8s manifesti içinden SecretRef ile alınıyor, burada tekrar env'e gerek yok.
          # Sadece IMAGE_TO_DEPLOY_AUTHSERVICE'i set etmek yeterli.
          IMAGE_TO_DEPLOY_AUTHSERVICE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}/${{ env.AUTH_SERVICE_IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag_sha_short }}
        run: |
          kubectl apply -f kubernetes-manifests/authservice.yaml --namespace=${{ env.K8S_NAMESPACE }}
          echo "Setting image for AuthService deployment to: ${IMAGE_TO_DEPLOY_AUTHSERVICE}"
          kubectl set image deployment/authservice authservice=${IMAGE_TO_DEPLOY_AUTHSERVICE} --namespace=${{ env.K8S_NAMESPACE }}
          echo "Waiting for AuthService rollout..."
          kubectl rollout status deployment/authservice --namespace=${{ env.K8S_NAMESPACE }} --timeout=240s

      - name: Install tools for E2E tests (nc)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y netcat-openbsd

      - name: Port-forward AuthService gRPC for E2E tests
        run: |
          echo "Starting AuthService port-forward (50051 -> 50051) for E2E tests..."
          nohup kubectl port-forward svc/authservice 50051:50051 -n ${{ env.K8S_NAMESPACE }} > pf_auth_e2e.log 2>&1 &
          sleep 15 # Port forward'ın başlaması ve servisin tam hazır olması için daha fazla bekle

      - name: Wait for gRPC port (50051) to be ready on localhost (for E2E)
        run: |
          echo "Waiting for localhost:50051 (AuthService for E2E) to be ready..."
          max_retries=20; count=0
          until nc -z localhost 50051; do
            if [ ${count} -ge ${max_retries} ]; then echo "Port 50051 (AuthService) did not become ready for E2E."; cat pf_auth_e2e.log; exit 1; fi
            echo "Port 50051 (AuthService for E2E) unavailable - sleeping"; sleep 3; count=$((count+1))
          done
          echo "Port 50051 (AuthService for E2E) is up!"

      - name: Run E2E Tests
        working-directory: ./src/authservice
        env:
          AUTH_SERVICE_ADDR_E2E_TEST: "localhost:50051"
          # CI_TEST_ENV: "true" # E2E testler için de DB ayarları gerekebilir, ama E2E testler canlı servise bağlanıyor.
                              # Servis zaten K8s içindeki DB'ye bağlanıyor.
        run: go test -v -race ./e2e/... -timeout 3m

      - name: Tear down AuthService port-forward (Best effort)
        if: always()
        run: |
          echo "Attempting to kill AuthService port-forward process..."
          pkill -f "kubectl port-forward svc/authservice 50051:50051" || echo "AuthService Port-forward not found or already killed."

      - name: Verify Deployments (Final Log Check)
        if: always()
        run: |
          echo "Final check of deployments in namespace: ${{ env.K8S_NAMESPACE }}"
          kubectl get all -n ${{ env.K8S_NAMESPACE }}
          echo "--- AuthService Logs (Last 100 lines) ---"
          kubectl logs deployment/authservice -n ${{ env.K8S_NAMESPACE }} --tail=100 || echo "AuthService logs could not be retrieved."
          echo "--- PostgreSQL Logs (Last 100 lines) ---"
          kubectl logs deployment/postgres-auth-deployment -n ${{ env.K8S_NAMESPACE }} --tail=100 || echo "PostgreSQL logs could not be retrieved."